feature/Att-kunna-bestmma-stegprocessen-CU-8wqa48
helsingborg-stad/mitt-helsingborg-form-builder pull request #4
Opened 2020-10-08 09:01 UTC by TeddyAndersson

Adding functionality to decide the navigation between steps in a form. 

First test of clickup github integration.

2020-10-08 09:01 UTC, TeddyAndersson commented
Task linked: [CU-8wqa48 Att kunna bestämma stegprocessen](https://app.clickup.com/t/8wqa48)

2020-10-09 07:36 UTC, jwinding requested changes
Much cleaner and easier to understand logic after the rewrite. My comments are just various clean-ups, and some consistency so that we don't use duplicate types.

2020-10-09 07:36 UTC, jwinding commented on src/components/specific/FormBuilder.tsx
> +// }
Remove this rather than commenting it out.

2020-10-09 07:36 UTC, jwinding commented on src/helpers/connectivityMatrix.ts
> +  console.log(matrix);
remove console log

2020-10-09 07:36 UTC, jwinding commented on src/types/FormTypes.ts
> +export type StepperActions = 'next' | 'back' | 'up' | 'down' | 'none';
Since we now export this type from the helper, we should probably only use that type everywhere, so this should be removed.

2020-10-09 07:36 UTC, jwinding commented on src/types/FormTypes.ts
> +  connectivityMatrix: StepperActions[][];
Same thing, use the types from the helper.

2020-10-09 07:36 UTC, jwinding commented on src/components/specific/Questions/NavigationButtonInput.tsx
> +import { Form, StepperActions } from '../../../types/FormTypes';
Use type from helper instead of the StepperAction type, here and in the rest of the file.

2020-10-09 16:51 UTC, dannil76 commented
Have opinion the use of non english language in branch name.

2020-10-09 16:53 UTC, dannil76 commented
What happened to the routine of working with a develop branch?!

2020-10-09 16:54 UTC, dannil76 requested changes
See comments about pr name and the lack of a develop branch

2020-10-15 11:20 UTC, TeddyAndersson commented
> Have opinion about the use of non english language in pr name.

Yeah i know it was a test with Clickup, it outgenerates the PR-Name :)

2020-10-15 11:21 UTC, TeddyAndersson commented
> > Have opinion about the use of non english language in pr name.
> 
> Yeah i know it was a test with Clickup, it outgenerates the PR-Name :)

So the branch name should still be in english (y)

2020-10-15 11:22 UTC, TeddyAndersson commented
> What happened to the routine of working with a develop branch?!

Also noticed this, we need to fix this asap. It's the lack of guidelines to how a repo should be organized :)

2020-10-24 11:39 UTC, dannil76 approved these changes

2020-11-16 14:39 UTC, dannil76 commented
Please recreate this pr to be rebased into develop

2021-02-03 09:21 UTC, closed without merging