feat: add new file picker component
helsingborg-stad/mitt-helsingborg-form-builder pull request #62
Opened 2022-05-10 07:45 UTC by kajm

**What was done**
Added new component (filepicker) for uploading both images and pdf:s in the same component

**How was it done**
Added the new component type as other components are added in formbuilder.

**Why was it done in this way**
This is how its done

**How was it tested**
Changed a form that uses the new component and tested it in the application

2022-05-10 07:48 UTC, helsingborgsstad commented
Task linked: [CU-2qa1knt Skapa ny komponent i formbuildern för att kunna ladda upp filer](https://app.clickup.com/t/2qa1knt)

2022-05-12 11:17 UTC, MasterKenth requested changes

2022-05-12 11:17 UTC, MasterKenth commented on src/components/specific/Questions/QuestionField.tsx
> +  { selectValue: 'bulletList', displayName: 'Bullet list', inputType: 'bulletList' },
Duplicate `bulletList`?

2022-05-12 14:34 UTC, kajm commented on src/components/specific/Questions/QuestionField.tsx
> +  { selectValue: 'bulletList', displayName: 'Bullet list', inputType: 'bulletList' },
fixed

2022-05-13 11:55 UTC, MasterKenth approved these changes

2022-05-13 11:56 UTC, merged